
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export PS1="\u@\h \[\033[95m\](\$(pwd))\[\033[00m\]\[\033[32m\]\$(parse_git_branch)\[\033[00m\] $ "


alias gfp="git fetch -p"
alias gco="git checkout"
alias gbr="git branch -r"
alias gbd="git branch -d"
alias gs="git status"
